// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_d5FrzM3OAwXHC4caG2ppmnHfG7LGv_w',
    appId: '1:636745926786:web:e2c56f3ab818fe578e4c9b',
    messagingSenderId: '636745926786',
    projectId: 'epistola-434b7',
    authDomain: 'epistola-434b7.firebaseapp.com',
    storageBucket: 'epistola-434b7.firebasestorage.app',
    measurementId: 'G-CST8DBH89X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWFu9QITMQrDmkV5pXkEfDvR4I3Jk0UvA',
    appId: '1:636745926786:android:e5fb63f4eb7e59528e4c9b',
    messagingSenderId: '636745926786',
    projectId: 'epistola-434b7',
    storageBucket: 'epistola-434b7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuKp_TCUEP9UEcbKi93olN6D5JM5NNuyM',
    appId: '1:636745926786:ios:dce4f8c000848ab28e4c9b',
    messagingSenderId: '636745926786',
    projectId: 'epistola-434b7',
    storageBucket: 'epistola-434b7.firebasestorage.app',
    iosBundleId: 'com.example.epistola',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuKp_TCUEP9UEcbKi93olN6D5JM5NNuyM',
    appId: '1:636745926786:ios:dce4f8c000848ab28e4c9b',
    messagingSenderId: '636745926786',
    projectId: 'epistola-434b7',
    storageBucket: 'epistola-434b7.firebasestorage.app',
    iosBundleId: 'com.example.epistola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_d5FrzM3OAwXHC4caG2ppmnHfG7LGv_w',
    appId: '1:636745926786:web:39abc834d8a7e7ce8e4c9b',
    messagingSenderId: '636745926786',
    projectId: 'epistola-434b7',
    authDomain: 'epistola-434b7.firebaseapp.com',
    storageBucket: 'epistola-434b7.firebasestorage.app',
    measurementId: 'G-T51KTGN8X6',
  );
}
