// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfuv0DI5AC_otHZn8zwHFEvLAHQ1VeTqg',
    appId: '1:995006917916:web:4fad7f564a305b2e8aded9',
    messagingSenderId: '995006917916',
    projectId: 'epistola-app',
    authDomain: 'epistola-app.firebaseapp.com',
    storageBucket: 'epistola-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_3erbskZmbSSU7m9nNk679aVycMgTgE',
    appId: '1:995006917916:android:573a75e9a577391e8aded9',
    messagingSenderId: '995006917916',
    projectId: 'epistola-app',
    storageBucket: 'epistola-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQQw3-ao0rkz16ZOm_wQjuTsuH3KrRKA',
    appId: '1:995006917916:ios:389825d8eb02a9b08aded9',
    messagingSenderId: '995006917916',
    projectId: 'epistola-app',
    storageBucket: 'epistola-app.firebasestorage.app',
    iosBundleId: 'com.example.epistola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQQw3-ao0rkz16ZOm_wQjuTsuH3KrRKA',
    appId: '1:995006917916:ios:389825d8eb02a9b08aded9',
    messagingSenderId: '995006917916',
    projectId: 'epistola-app',
    storageBucket: 'epistola-app.firebasestorage.app',
    iosBundleId: 'com.example.epistola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfuv0DI5AC_otHZn8zwHFEvLAHQ1VeTqg',
    appId: '1:995006917916:web:5b648683689d8ab38aded9',
    messagingSenderId: '995006917916',
    projectId: 'epistola-app',
    authDomain: 'epistola-app.firebaseapp.com',
    storageBucket: 'epistola-app.firebasestorage.app',
  );
}
